name: Java Build with setup-java

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 11 (Zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Spotless
        run: ./gradlew :spotlessApply

      - name: Build Application
        run: ./gradlew clean build
