name: Java Build and Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 11 (Zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Spotless
        run: ./gradlew :spotlessApply

      - name: Build Application
        run: ./gradlew clean build

      - name: Rename JAR files to match secret
        run: |
          mkdir output
          for f in build/libs/*.jar; do
            cp "$f" "output/${{ secrets.JAR_FILE_NAME }}-${f##*/}"
          done

      - name: Upload JAR files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-jar
          path: output/*.jar
